apiVersion: v1
kind: Service
metadata:
  name: {{ include "inventory-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "inventory-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "inventory-service.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http