prometheus:
  url: http://kube-prometheus-stack-prometheus.monitoring.svc
  port: 9090

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

rules:
  default: false
  custom:
    - seriesQuery: 'order_active_requests{namespace!="",pod!=""}'
      resources:
        overrides:
          namespace:
            resource: "namespace"
          pod:
            resource: "pod"
      name:
        matches: "order_active_requests"
        as: "order_active_requests"
      metricsQuery: 'avg(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)'