fullnameOverride: tempo

tempo:
  reportingEnabled: false
  memBallastSizeMbs: 0

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

  retention: 24h

  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

persistence:
  enabled: true
  storageClassName: standard-rwo
  size: 5Gi

service:
  type: ClusterIP

serviceMonitor:
  enabled: true