replicaCount: 2

image:
  repository: asia-south1-docker.pkg.dev/iconic-being-499605-m3/order-app/inventory-service
  tag: latest
  pullPolicy: Always

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

namespace: order-app

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8001"
  prometheus.io/path: "/metrics"

podLabels: {}

podSecurityContext:
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 8001
  targetPort: 8001

containerPort: 8001

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

startupProbe:
  httpGet:
    path: /health
    port: 8001
  initialDelaySeconds: 2
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 12

readinessProbe:
  httpGet:
    path: /health
    port: 8001
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /health
    port: 8001
  initialDelaySeconds: 10
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 5

env:
  OTEL_SERVICE_NAME: inventory-service

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Pods
      pods:
        metric:
          name: inventory_active_requests
        target:
          type: AverageValue
          averageValue: "10"